export const GAME_CONSTANTS = {
  MAX_NIVEL_QUEIMADA: 3,
  MAX_TRILHA_QUEIMADA: 100,
  MAX_TRILHA_FLORA: 100,
  MIN_TRILHA_FLORA: 0,
  MAX_TURNOS: 30,
  ACOES_POR_TURNO: 4,
  CARTAS_INICIAIS_POR_JOGADOR: 2,
  QUEIMADAS_INICIAIS: 3,
  AUMENTO_CHANCE_QUEIMADA_NATURAL: 0.2, // 20% de chance de queimada aumentar de nível naturalmente
  AUMENTO_TRILHA_QUEIMADA_SURTO: 10,
  RECUPERACAO_FLORA_TURNO_PADRAO: 5,
  DEGRADACAO_FLORA_TURNO_PADRAO: 5,
  NIVEL_QUEIMADA_PARA_RECUPERACAO_FLORA: 50, // Se trilhaQueimada < 50, flora recupera
  FATORES_EVENTOS: {
    SECA_PROLONGADA_AUMENTO_QUEIMADA: 15,
    CHUVA_BENEFICA_REDUCAO_QUEIMADA: 1,
    CHUVA_BENEFICA_AUMENTO_FLORA: 10,
    CHUVA_BENEFICA_AUMENTO_FLORA_SEM_QUEIMADA: 5,
    CONSCIENTIZACAO_AUMENTO_PROTECAO: 20,
    VERBA_EMERGENCIAL_ACOES_EXTRA: 1,
  },
  VITORIA_FLORA_LIMIAR: 80, // Nível de flora para vitória
  NUM_CARTAS_QUEIMADA_POR_FASE: (trilhaQueimada: number) => Math.floor(trilhaQueimada / 20) + 1, // Ex: 0-19: 1 carta, 20-39: 2 cartas, etc.
  MAX_LOG_MESSAGES: 100,
};