name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  
jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Test With Coverage
        run: npm run core:test:coverage

      - name: Upload Coverage
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          name: coverage-core
          path: packages/core/coverage/

  test-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Test With Coverage
        run: npm run react:test:coverage

      - name: Upload Coverage
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          name: coverage-react
          path: packages/react/coverage/

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  deploy-coverage:
    if: always()
    needs: [test-core, test-react]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download core coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-core
          path: site/core

      - name: Download react coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-react
          path: site/react

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4